import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { StorageDriver } from "../types";

/**
 * Writes uploaded documents to a folder on this machine (`./storage` by
 * default, or STORAGE_DIR if you set it).
 *
 * Good enough for a single server you control, and it is what the README's
 * Option A recommends. NOT suitable for Vercel: that filesystem is wiped on
 * every deploy, so every client's bond and insurance paperwork would vanish.
 */

/** Where files land. Resolved once so every path check below shares a root. */
const ROOT = path.resolve(process.env.STORAGE_DIR ?? "storage");

/**
 * Turn a key into an absolute path, refusing anything that escapes ROOT.
 *
 * Keys are generated by `buildStorageKey`, but they make a round trip through
 * the database before `get`/`delete` see them again. Re-checking here means a
 * tampered `storageKey` column cannot be used to read /etc/passwd.
 */
function resolveWithinRoot(key: string): string {
  const full = path.resolve(ROOT, key);
  const prefix = ROOT + path.sep;

  if (full !== ROOT && !full.startsWith(prefix)) {
    throw new Error(`[storage] Refusing to touch a path outside the storage root: ${key}`);
  }

  return full;
}

export const localDriver: StorageDriver = {
  name: "local",

  async put(key, data) {
    const full = resolveWithinRoot(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, data);
  },

  async get(key) {
    try {
      return await readFile(resolveWithinRoot(key));
    } catch (error) {
      // A missing file is an expected outcome — the caller renders a 404.
      if ((error as NodeJS.ErrnoException)?.code === "ENOENT") return null;
      throw error;
    }
  },

  async delete(key) {
    // `force` so deleting an already-deleted document is a no-op.
    await rm(resolveWithinRoot(key), { force: true });
  },
};
